<?php
echo $this->flashMessages();
?>

<br/><br/>
<div id="view-content">
    <style>
        .colorme {
            height: 30px;
            width: 30px;
            display: block;
            border-radius: 3px;
        }
    </style>
    <h1>Frucht Übersicht</h1>

    <div class="table-responsive">
        <a href="<?php echo $this->url(array(
            'controller' => "Fruits",
            "action"     => "add"
        )) ?>" data-target="#newFruit" class="btn btn-success pull-right"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            Neue Frucht</a>


        <table class="table table-striped">
            <thead>
            <tr>
                <th>Fruchtname</th>
                <th class="text-center">Bild</th>
                <th>Beschreibung</th>
                <th class="text-right" data-toggle="tooltip" data-placement="top" title="Tooltip on left">Kalorien</th>
                <th>Farbe</th>
                <th class="text-right">Preis</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php

            if (count($this->allFruits) < 1) {
                ?>
                <tr>
                    <td colspan="7">Keine Früchte vorhanden</td>
                </tr>
            <?php
            }

            foreach ($this->allFruits as $fruit) { ?>
                <tr>
                    <td><?php echo $fruit->getName() ?></td>
                    <td class="text-center"><img src="<?php echo $fruit->getPicture() ?>" alt="" width="48" height="48">
                    </td>
                    <td><?php echo $fruit->getDescription() ?></td>
                    <td class="text-right"><?php echo $fruit->getKcal() ?> kcal</td>
                    <td><span class="colorme" style="background-color:<?php echo $fruit->getColor() ?>"></span></td>
                    <td class="text-right">&euro; <?php echo number_format($fruit->getPrice(), 2, ",", ".") ?></td>
                    <td class="text-right">
                        <form action="<?php echo $this->url(array(
                            "controller" => "fruits",
                            "action"     => "delete"
                        )) ?>" method="post">
                            <button name="id" data-btn-ok-label="Ja" data-btn-ok-icon="glyphicon glyphicon-share-alt" data-btn-ok-class="btn-success" data-btn-cancel-label="Nein" data-btn-cancel-icon="glyphicon glyphicon-ban-circle" data-btn-cancel-class="btn-danger" value="<?php echo $fruit->getId() ?>" class="btn btn-danger fruit-delete" type="submit">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> L&ouml;schen
                            </button>
                        </form>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>

</div>