<?php
$form = $this->registerForm;
?>

<form enctype="application/x-www-form-urlencoded" method="
<?php echo $form->getAttribs()["method"] ?>" name="
<?php echo $form->getAttribs()["name"] ?>" id="
<?php echo $form->getAttribs()["name"] ?>">

    <div class="container">
        <h1>Registerungsformular</h1>
        <p>Hier können sie sich ganz einfach kostenlos registerieren</p>
        <class="row">
            <div class="col-md-4">
                <img src="img/smoothieglas.png" alt="" style="margin-left:-100px">
            </div>
            <div class="col-md-8">
                <div class="col-md-4"><?php echo $form->surname; ?></div>
                <div class="col-md-4"><?php echo $form->lastname; ?></div>
                <div class="col-md-8"><?php echo $form->email; ?></div>
                <div class="col-md-8"><?php echo $form->telephone; ?></div>
                <div class="col-md-8"><?php echo $form->gender; ?></div>
                <div class="col-md-8"><?php echo $form->password; ?></div>
                <div class="col-md-8"><?php echo $form->password2; ?></div>
                <div class="col-md-8"><?php echo $form->captcha; ?></div>
                <div class="col-md-8"><?php echo $form->submit; ?></div>
            </div>
        </div>
    </div>
</form>