<div class="container">
    <div  class="register-head">
        <h1>Registerungsformular</h1>
        <p>Hier können sie sich ganz einfach kostenlos registerieren</p>
    </div>
    <div class="row">
        <div class="col-md-5">
            Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
            sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
            ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore
            magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata
            sanctus est Lorem ipsum dolor sit amet.
        </div>
        <div class="col-md-7">
            <form class=form-horizontal" role="form">
                <?php
                $this->form->setAction($this->url());
                echo $this->form;
                ?>
            </form>
            <p>*) Pflichtfelder</p>

        </div>
    </div>
</div>

