<?php
$form = $this->registerForm;

//Nicht ausgegebene Ereignisse des aktuellen Requests
if ($this->unfullfilledRequiredments) {
    echo $this->flashMessages(true);
} else {
    echo $this->flashMessages();
}
?>

    <div class="container">
        <h1>Registerungsformular</h1>
        <p>Hier können sie sich ganz einfach kostenlos registerieren</p>
        <div class="row">
            <img class="col-md-5 col-xs-2" src="img/smoothieglas.png" alt="Strawberryshake" style="margin-left:-100px">
            <div class="col-md-8">
                <form class="form-group" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>">
                    <div class="row"><div class="col-md-8"><?php echo $form->username; ?></div></div>
                    <div class="row"><div class="col-md-4"><?php echo $form->surname; ?></div>
                        <div class="col-md-4"><?php echo $form->lastname; ?></div></div>
                    <div class="row"><div class="col-md-8"><?php echo $form->email; ?></div></div>
                    <div class="row"><div class="col-md-8"><?php echo $form->telephone; ?></div></div>
                    <div class="row"><div class="col-md-8"><?php echo $form->gender; ?></div></div>
                    <div class="row"><div class="col-md-8"><?php echo $form->password; ?></div></div>
                    <div class="row"><div class="col-md-8"><?php echo $form->password2; ?></div></div>
                    <div class="row"><div class="col-md-8"><?php echo $form->captcha; ?></div></div>
                    <div class="row"><div class="col-md-8"><?php echo $form->submit; ?></div></div>
                </form>
            </div>
        </div>
    </div>
