
    <div class="row">
        <div class="container">
        <div class="jumbotron">
        <h1>Willkommen auf smoothieme.de</h1>
        <p>Wir bringen Ihnen Ihren Lieblingssmoothie vor die Haustüre.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Jetzt Los Mixen!</a></p>
        </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/img/thumbnail_1.jpg" data-src="holder.js/100%x200" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>Das Wort Smoothie erschien erstmals 1904 in einem US-amerikanischen Wörterbuch, jedoch mit einer völlig anderen Bedeutung. Damals wurde so eine Person bezeichnet, die entweder sehr redegewandt war oder besonders gute Manieren hatte. Einige Zeit später wurde der Begriff von Herstellern als Name für ganz unterschiedliche Produkte verschiedener Branchen verwendet. 1969 wurde der Name Cream Smoothie für die Softdrinks eines Herstellers gesetzlich geschützt. Als Bezeichnung für ein Fruchtsaftgetränk wurde Smoothie erstmals Mitte der 1970er Jahre verwendet, und zwar als California Smoothie von der Firma California Smoothie Company of Paramus. Als Name für ein Ganzfruchtgetränk wurde der Begriff erst in den 1980er Jahren popularisiert.</p>
                    <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/img/thumbnail_2.jpg" data-src="holder.js/100%x200" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>Trotz seiner offensichtlichen Nachteile (schwer, zerbrechlich, teurer) haben wir uns 2006 ganz bewusst für Glasflaschen entschieden. In unseren Augen ist es halt einfach das beste Verpackungsmaterial. Warum? Im Gegensatz zu PET tauscht sich Glas nicht mit seiner Umwelt aus. Das bedeutet: Glas ist wie ein Tresor. Es nimmt keinen Geschmack an und gibt keinen Geschmack ab. Außerdem wird Glas ausschließlich aus natürlichen Rohstoffen hergestellt (für alle die es genau wissen wollen: 70% Quarzsand (SiO2), 13% Soda (Na2CO3), 10% Kalk (CaCO3) und geringe Anteile Dolomit, Feldspat sowie etwas Pottasche) und was das Ganze noch toppt: GLAS IST SCHLICHT UND EINFACH SCHÖN!!! Wir sind halt nicht nur echte Frucht-, sondern auch Glasfetischisten (also was die Verpackung von Lebensmittel angeht, nicht was ihr Euch jetzt wieder gedacht habt).</p>
                    <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/img/thumbnail_3.jpg" data-src="holder.js/100%x200" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>Das Wort Smoothie erschien erstmals 1904 in einem US-amerikanischen Wörterbuch, jedoch mit einer völlig anderen Bedeutung. Damals wurde so eine Person bezeichnet, die entweder sehr redegewandt war oder besonders gute Manieren hatte. Einige Zeit später wurde der Begriff von Herstellern als Name für ganz unterschiedliche Produkte verschiedener Branchen verwendet. 1969 wurde der Name Cream Smoothie für die Softdrinks eines Herstellers gesetzlich geschützt. Als Bezeichnung für ein Fruchtsaftgetränk wurde Smoothie erstmals Mitte der 1970er Jahre verwendet, und zwar als California Smoothie von der Firma California Smoothie Company of Paramus. Als Name für ein Ganzfruchtgetränk wurde der Begriff erst in den 1980er Jahren popularisiert.</p>
                    <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
            </div>
        </div>
    </div>

