<?php
//Nicht ausgegebene Ereignisse des Letzten Requests
echo $this->flashMessages();
//Nicht ausgegebene Ereignisse des aktuellen Requests
echo $this->flashMessages(true);
?>
    <div class="row carousel_style">
        <div class="container">
            <div id="carousel_smoothieme" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel_smoothieme" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel_smoothieme" data-slide-to="1"></li>
                    <li data-target="#carousel_smoothieme" data-slide-to="2"></li>
                    <li data-target="#carousel_smoothieme" data-slide-to="3"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="img/fruitsstart_slide.jpg" alt="...">
                    </div>
                    <div class="item">
                        <img src="img/fruits1_slide.jpg" alt="...">
                    </div>
                    <div class="item">
                        <img src="img/fruits2_slide.jpg" alt="...">
                    </div>
                    <div class="item">
                        <img src="img/fruits3_slide.jpg" alt="...">
                    </div>
                    </div>

                </div>

                <!-- Controls -->
               <!-- <a class="left carousel-control" href="#carousel_smoothieme" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel_smoothieme" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>-->
            </div>
       </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/img/thumbnail_1.jpg" data-src="holder.js/100%x200" alt="...">
                <div class="caption">
                    <h3>Woher das Wort "Smoothie"?</h3>
                    <p>Das Wort Smoothie erschien erstmals 1904 in einem US-amerikanischen Wörterbuch, jedoch mit einer völlig anderen Bedeutung. Damals wurde so eine Person bezeichnet, die entweder sehr redegewandt war oder besonders gute Manieren hatte. Einige Zeit später wurde der Begriff von Herstellern als Name für ganz unterschiedliche Produkte verschiedener Branchen verwendet. 1969 wurde der Name Cream Smoothie für die Softdrinks eines Herstellers gesetzlich geschützt. Als Bezeichnung für ein Fruchtsaftgetränk wurde Smoothie erstmals Mitte der 1970er Jahre verwendet, und zwar als California Smoothie von der Firma California Smoothie Company of Paramus. Als Name für ein Ganzfruchtgetränk wurde der Begriff erst in den 1980er Jahren popularisiert.</p>

                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/img/thumbnail_2.jpg" data-src="holder.js/100%x200" alt="...">
                <div class="caption">
                    <h3>Warum Glas?</h3>
                    <p>Trotz seiner offensichtlichen Nachteile (schwer, zerbrechlich, teurer) haben wir uns 2006 ganz bewusst für Glasflaschen entschieden. In unseren Augen ist es halt einfach das beste Verpackungsmaterial. Warum? Im Gegensatz zu PET tauscht sich Glas nicht mit seiner Umwelt aus. Das bedeutet: Glas ist wie ein Tresor. Es nimmt keinen Geschmack an und gibt keinen Geschmack ab. Außerdem wird Glas ausschließlich aus natürlichen Rohstoffen hergestellt (für alle die es genau wissen wollen: 70% Quarzsand (SiO2), 13% Soda (Na2CO3), 10% Kalk (CaCO3) und geringe Anteile Dolomit, Feldspat sowie etwas Pottasche) und was das Ganze noch toppt: GLAS IST SCHLICHT UND EINFACH SCHÖN!!! Wir sind halt nicht nur echte Frucht-, sondern auch Glasfetischisten (also was die Verpackung von Lebensmittel angeht, nicht was ihr Euch jetzt wieder gedacht habt).</p>

                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/img/thumbnail_3.jpg" data-src="holder.js/100%x200" alt="...">
                <div class="caption">
                    <h3>Gute Kalorien</h3>
                    <p>Eine Kalorie (cal) ist eine Einheit zur Messung von Energie. Wir brauchen Energie, um unseren Körper und unser Gehirn am Laufen zu halten. Stärke und Zucker sind Kohlenhydrate und liefern beide 4 kcal pro Gramm. Fett enthält mehr als das Doppelte an Kalorien, nämlich 9 kcal pro Gramm.
                        Weil die meisten Früchte nur wenig Fett enthalten, haben auch unsere Smoothies fast kein Fett. Weil Früchte aber Zucker enthalten, kommt auch die meiste Energie in unseren Smoothies vom natürlich enthaltenen Fruchtzucker.
                        Du erinnerst Dich bestimmt, dass jede unserer 250 ml-Flaschen ganze zwei Portionen Frucht enthält. Für jede Kalorie bekommst Du also eine Menge guter Vitamine, Ballaststoffe und Nährstoffe.
                        Eine 250 ml-Flasche eines innocent Smoothies versorgt Dich mit 120 bis 190 kcal. Das sind nur 6 % bis 9 % der Kalorien, die Du täglich zu Dir nehmen solltest.</p>
                </div>
            </div>
        </div>
    </div>

