<?php

$form = $this->addressForm;

//Nicht ausgegebene Ereignisse des aktuellen Requests
if ($this->unfullfilledRequiredments) {
	echo $this->flashMessages(true);
} else {
	echo $this->flashMessages();
}

?>

<div class="panel panel-default">
	<div class="panel-heading"><h1>Neue Addresse</h1></div>
		<div class="panel-body">

			<form enctype="application/x-www-form-urlencoded" action="<?php echo $form->getAttribs()["action"] ?>"
				  method="<?php echo $form->getAttribs()["method"] ?>"
				  name="<?php echo $form->getAttribs()["name"] ?>"
				  id="<?php echo $form->getAttribs()["name"] ?>">

				<div class="row">
					<div class="col-sm-8">
						<div class="col-sm-9" <?php echo $form->street->hasErrors() ? "has-error" : null; ?>"><?php echo $form->street; ?></div>
						<div class="col-sm-3" <?php echo $form->number->hasErrors() ? "has-error" : null; ?>"><?php echo $form->number; ?></div>
						<div class="col-sm-5" <?php echo $form->zip->hasErrors() ? "has-error" : null; ?>"><?php echo $form->zip; ?></div>
						<div class="col-sm-7" <?php echo $form->country->hasErrors() ? "has-error" : null; ?>"><?php echo $form->country; ?></div>
					</div>
				</div>
			<div class="col-sm-12" ><?php echo $form->submit ?></div>
		</form>
	</div>
</div>