<div class="row">
    <div class="col-md-7">
        <h3>Adresse ändern</h3>
        <div class="row">
            <div class="col-md-8 col-sm-7 col-xs-6">
                <div class="form-group">
                    <label for="street">Straße</label>
                    <input type="text" class="form-control" value="Musterstraße">
                </div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-2">
                <div class="form-group">
                    <label for="street">Nr.</label>
                    <input type="text" class="form-control" value="1">
                </div>
            </div>
            <br>
            <div class="col-xs-3">
                <div class="form-group">
                    <label for="zip">Postleitzahl</label>
                    <input type="text" class="form-control" value="123456">
                </div>
            </div>
            <div class="col-xs-7">
                <div class="form-group">
                    <label for="city">Ort</label>
                    <input type="text" class="form-control" value="Musterstadt">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-default">Adresse ändern</button>
        <br><br><br>

        <h3>Neue Adresse anlegen</h3>
        <div class="row">
            <div class="col-md-8 col-sm-7 col-xs-6">
                <div class="form-group">
                    <label for="street">Straße</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-2">
                <div class="form-group">
                    <label for="street">Nr.</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <br>
            <div class="col-xs-3">
                <div class="form-group">
                    <label for="zip">Postleitzahl</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="col-xs-7">
                <div class="form-group">
                    <label for="city">Ort</label>
                    <input type="text" class="form-control">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-default">Neue Adresse anlegen</button>
        <br><br><br>

        <h3>Bestehende Adresse löschen</h3>
        <div class="row">
            <div class="col-md-8 col-sm-7 col-xs-6">
                <div class="form-group">
                    <label for="street">Straße</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-2">
                <div class="form-group">
                    <label for="street">Nr.</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <br>
            <div class="col-xs-3">
                <div class="form-group">
                    <label for="zip">Postleitzahl</label>
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="col-xs-7">
                <div class="form-group">
                    <label for="city">Ort</label>
                    <input type="text" class="form-control">
                </div>
            </div>
        </div>
    <button type="submit" class="btn btn-default">Adresse löschen</button>
    </div>
</div>
<br><br><br>