<!--
<form accept-charset="UTF-8" role="form">
    <fieldset>
        <div class="form-group">
            <input class="form-control" placeholder="E-Mail" name="email" type="text">
        </div>
        <div class="form-group">
            <input class="form-control" placeholder="Passwort" name="password" type="password"
                   value="">
        </div>
        <div class="checkbox">
            <label>
                <input name="remember" type="checkbox" value="Remember Me"> An mich erinnern
            </label>
        </div>
        <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
    </fieldset>
</form> -->


            <?php echo $this->loginForm; ?>
