<?php
echo $this->flashMessages();
?>
<div class="panel panel-default " id="smoothies-index">
	<div class="panel-heading clearfix ">
		<h1 class="pull-left ">Smoothies Übersicht</h1>
	</div>
	<table class="table table-striped">
		<thead>
		<tr>
			<th>Name</th>
			<th>Früchte</th>
			<th class="text-right">Preis</th>
			<th>Erstellt von</th>
			<th>&nbsp;</th>
		</tr>
		</thead>
		<tbody>
		<?php

		if (count($this->smoothies) < 1) {
			?>
			<tr>
				<td colspan="5">Keine Smoothies vorhanden</td>
			</tr>
		<?php
		}

		foreach ($this->smoothies as $smoothie) {
			?>
			<tr>
				<td><?php echo $smoothie->getName() ?></td>
				<td class="text-left">
					<ul class="fruits-of-smoothie">
						<?php foreach ($smoothie->getFruits() as $fruit) {
							$fruit["fruit"]->isUsed();
							?>
							<li><img src="<?php echo $fruit["fruit"]->getPicture() ?>"/>
                                <span>
                                    <b><?php echo $fruit["fruit"]->getName() ?></b>
                                    <small>(<?php echo $fruit["amount"] ?>ml)</small>
                            </span></li>
						<?php } ?>
					</ul>
				</td>
				<td class="text-right vcenter">&euro; <?php echo number_format($smoothie->getPrice(), 2, ".", ","); ?></td>
				<td>
					<?php
					if(is_null($smoothie->getCustomer())){
						echo "- öffentlicher Smoothie -";
					}else{
						echo $smoothie->getCustomer()->getSurname()." ".$smoothie->getCustomer()->getLastname();
					}
					?>
				</td>
				<td class="text-right">
					<!--                    <button type="button" class="btn btn-info pull-right"> <span-->
					<!--                            class="glyphicon glyphicon-edit" aria-hidden="true"></span>-->
					<!--                        <span class="hidden-xs">bearbeiten</span>-->
					<!--                    </button>-->
					<form action="<?php echo $this->url(array(
						"controller" => "smoothies-user",
						"action"     => "addtocart"
					)) ?>" method="post">
						<button class="btn btn-success" type="submit" >
							<input type="hidden" name="addtocart" value="<?php echo $smoothie->getId()?>" />
							<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
							<span class="hidden-xs">In Warenkorb legen</span>
						</button>
					</form>

				</td>
			</tr>
		<?php } ?>
		</tbody>

	</table>

</div>