<ul class="adminmenu nav navbar-nav navbar-right">
    <li><a href="#"><b>Logout</b></a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
           aria-expanded="false"><b>Admin-Bereich</b><span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Bestellungen</a></li>
            <li class="divider"></li>
            <li><a href="#">Benutzereinstellungen</a></li>
            <li class="divider"></li>
            <li><a href="#">Smoothies</a></li>
        </ul>
    </li>
</ul>