<ul class="adminmenu nav navbar-nav navbar-right">
    <li><a href="<?php echo $this->url(array('controller' => "auth","action" => "logout"))?>"><b>Abmelden</b></a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
           aria-expanded="false"><b>Admin-Bereich</b><span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Bestellungen</a></li>
            <li class="divider"></li>
            <li><a href="#">Benutzereinstellungen</a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->url(array('controller' => "smoothies", "action"=>"index"))?>">Smoothies</a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->url(array('controller' => "fruits", "action"=>"index"))?>">Früchte</a></li>
        </ul>
    </li>
</ul>

