    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#example-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="<?php echo $this->url(array('controller' => "index", 'action'=> "index")) ?>"><img class="logo_small" src="/img/smoothiemelogo_small.png"></a>
    </div>
    <div class="collapse navbar-collapse" id="example-navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="#">Mix It</a></li>
            <li><a href="<?php echo $this->url(array('controller' => "smoothies", 'action' => "index")) ?>">Fertige Smoothies</a> </li>
        </ul>
        <?php
           if (Zend_Auth::getInstance()->hasIdentity()){
                if (Zend_Auth::getInstance()->getIdentity()->role === 'admin') {
                    require "admin.phtml";
                }
                else {
                    require "user.phtml";
                }
            }
            else {
                require "login.phtml";
            }
        ?>
     </div>


