    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#example-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <img class="logo_small" src="/img/smoothiemelogo_small.png">
    </div>
    <div class="collapse navbar-collapse" id="example-navbar-collapse">
        <ul class="nav navbar-nav">
            <li ><a href="<?php echo $this->url(array('controller' => "index")) ?>">Start</a></li>
            <li><a href="<?php echo $this->url(array('controller' => "smoothies")) ?>">Mix It</a></li>
            <li><a href="#">Fertige Smoothies</a> </li>
        </ul>
        <?php require_once "login.phtml" ?>
     </div>


