<ul class="loginmenu nav navbar-nav navbar-right">
    <li><a href=""><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
    <li data-toggle="modal" data-target="#modalwindow"><a href="#"><b>Anmelden</b></a></li>
    <li><a href="/register"><b>Registrieren</b></a></li>
</ul>
<div class="modal fade" id="modalwindow" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="ModalLabel">Bitte melden Sie sich an</h4>
            </div>
            <div class="modal-body">
                <div class="panel-body">
                    <?php echo $this->action("index", "auth") ?>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Schließen</button>
                </div>
            </div>
        </div>
    </div>
</div>