<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#example-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <img class="logo_small" src="/img/smoothiemelogo_small.png">
    </div>
    <div class="collapse navbar-collapse" id="example-navbar-collapse">
        <ul class="nav navbar-nav">
            <li ><a href="#">Start</a></li>
            <li><a href="#">Mix It</a></li>
            <li><a href="#">Fertige Smoothies</a> </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href=""><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
            <li ><a href="#"><b>Logout</b></a></li>
            <li  class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><b>Meine Einstellungen</b><span class="caret"></span></a>
                <ul  class="dropdown-menu" role="menu">
                    <li ><a href="#">Meine Bestellungen</a></li>
                    <li class="divider"></li>
                    <li ><a href="#">Profileinstellungen</a></li>
                    <li class="divider"></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>