<ul class="usermenu nav navbar-nav navbar-right">
    <li><a href=""><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
    <li><a href="<?php echo $this->url(array('controller' => "auth","action" => "logout")) ?>"><b>Abmelden</b></a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><b>Meine
                Einstellungen</b><span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Meine Bestellungen</a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->url(array('controller' => "user", 'action'=> "index"))?>">Profileinstellungen</a></li>
        </ul>
    </li>
</ul>