#!/bin/bash


group :development do
  guard :livereload do
    watch(%r{css/.+\.css})
    watch(%r{js/.+\.js})
  end

  if File.exists?("./config.rb")
    # Compile on start.
    puts `compass compile --time --quiet`
    guard :compass do
      watch(%r{^sass/(.+)\.scss$})
    end
  end
end
