<?php
$form = $this->smoothieForm;
echo $this->flashMessages(true);

?>

<div id="newSmoothie">
    <h1>Neuer Smoothie </h1>

    <form class="clearfix" enctype="application/x-www-form-urlencoded" action="<?php echo $form->getAttribs()["action"] ?>" method="<?php echo $form->getAttribs()["method"] ?>" name="<?php echo $form->getAttribs()["name"] ?>" id="<?php echo $form->getAttribs()["name"] ?>">
        <div class="pull-left smoothie-config col-xs-6 col-md-6 col-sm-6">
            <div class="row">
                <div class="col-xs-7 col-md-7 col-sm-7 <?php echo $form->name->hasErrors() ? "has-error" : null; ?>">
                    <?php echo $form->name ?>
                </div>

                <div class="col-xs-5 col-md-5 col-sm-5 <?php echo $form->name->hasErrors() ? "has-error" : null; ?>">
                    <?php echo $form->size ?>
                </div>

            </div>
            <br>

            <div class="row">
                <div class="col-xs-7 col-md-7 col-sm-7">
                    <button type="button" class="pull-left btn btn-success" data-toggle="modal" data-target=".insertnewFruit">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Frucht hinzufügen
                    </button>
                </div>
                <div class="col-xs-5 col-md-5 col-sm-5 text-right">
                    <?php echo preg_replace("/<dt[^>]+[^<]+<\/dt>/m", " ", $form->submit); ?>
                </div>
            </div>
            <hr>
            <div class="row  h4">
                <div class="col-xs-12 col-md-12 col-sm-12 text-right">
                    Preis &euro; <span id="summe">0,00</span>
                </div>
            </div>
            <hr>
            <div id="all-fruit-sliders">

            </div>
        </div>
        <div class="pull-right" id="mixerwrapper">
            <div class="fruitcolor">
                <div class="fruitwave" style="background-color:pink"></div>
                <div class="fruitbody" style="background-color:pink"></div>
            </div>
            <div class="fruitcolor">
                <div class="fruitwave" style="background-color:green"></div>
                <div class="fruitbody" style="background-color:green"></div>
            </div>
            <div class="fruitcolor">
                <div class="fruitwave" style="background-color:yellow"></div>
                <div class="fruitbody" style="background-color:yellow"></div>
            </div>
            <div class="fruitcolor">
                <div class="fruitwave" style="background-color:violet"></div>
                <div class="fruitbody" style="background-color:violet"></div>
            </div>
            <div class="fruitcolor">
                <div class="fruitwave" style="background-color:turquoise"></div>
                <div class="fruitbody" style="background-color:turquoise"></div>
            </div>
            <img src="/img/mixer.png" alt="the mixer" class="pull-right" id="mixer">
        </div>
        <div class="modal fade insertnewFruit" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span></button>
                        <h4 class="modal-title" id="mySmallModalLabel">Frucht für Smoothie wählen</h4>
                    </div>
                    <div class="modal-body">
                        <select name="Fruit-to-add">
                            <?php foreach ($this->fruits as $fruit) { ?>
                                <option data-pic="<?php echo $fruit->getPicture() ?>" data-name="<?php echo $fruit->getName() ?>" data-color="<?php echo $fruit->getColor() ?>" data-price="<?php echo $fruit->getPrice() ?>" id="<?php echo $fruit->getID() ?>" value="<?php echo $fruit->getID() ?>" data-subtext="je 100ml"><?php echo $fruit->getName() ?>
                                    - &euro; <?php echo number_format($fruit->getPrice(), 2, ",", ".") ?> </option>
                            <?php } ?>
                        </select>
                        <button id="btn-add-fruit" type="button" class="btn center-block btn-primary top-buffer">
                            Frucht hinzufügen
                        </button>

                    </div>
                </div>
            </div>
        </div>
    </form>
</div>