<br /><br />
<div id="view-content">
	<p>View script for controller <b>Smoothies</b> and script/action name <b>add</b></p>
</div>
<a data-toggle="modal" href="<?php echo $this->url(array('controller' => "Fruits")) ?>" data-target="#newFruit" type="button" class="btn btn-primary btn-lg">Neue Frucht anlegen</a>
<!-- Modal -->
<div class="modal fade" id="newFruit" tabindex="-1" >
	<div class="modal-dialog">
		<div class="modal-content">

		</div>
	</div>
</div>