<?php echo $this->doctype() ?>

<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>SmoothieMe</title>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
    <?php echo $this->headScript() ?>

    <?php echo $this->headLink() ?>

  <!--<base href="//<?php echo $_SERVER["SERVER_NAME"] ?>" />-->
</head>
<body>
<header>
    <nav class="menu" role="navigation">
        <?php echo $this->action("index","navigation") ?>
    </nav>
</header>
<main>
        <noscript><div class="alert alert-warning" role="alert"><h4>Warnung!</h4><p>Ihr Browser unterstützt womöglich kein Javascript. <br> Ohne Javascript kann diese Seite nicht Ordnungsgemäß angezeigt werden.<br> Prüfen Sie gegebenfalls Ihre Browsereinstellungen und aktivieren Sie Javascript.</p></div></noscript>
        <?php echo $this->layout()->content; ?>
</main>
<footer>
    Diese Seite ist ein Studien-Projekt und verfolgt weder kommerzielle noch redaktionelle Absichten.
    Abgeschlossene Bestellungen werden daher ignoriert!
</footer>

</body>
</html>
