<?php echo $this->doctype() ?>

<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>SmoothieMe</title>
    <?php echo $this->headScript() ?>

    <?php echo $this->headLink() ?>

</head>
<body>
<header>
    <nav>
        <?php echo $this->action("index","navigation") ?>
<!--        --><?php //echo $this->action("admin","navigation")?>
<!--        --><?php //echo $this->action("user","navigation")?>
    </nav>
</header>
<main>
        <?php echo $this->layout()->content; ?>
</main>
<footer>


</footer>

</body>
</html>
