<?php
$form = $this->userForm;

//Nicht ausgegebene Ereignisse des aktuellen Requests
if ($this->unfullfilledRequiredments) {
    echo $this->flashMessages(true);
} else {
    echo $this->flashMessages();
}
?>

<div class="row">
    <div class="col-sm-5 col-sm-offset-1">
        <h1>Profil</h1>
        <h3>Persönliches</h3>
        <div class="row">
            <div class="col-md-6"><?php echo $Form->surname; ?></div>
            <div class="col-md-6"><?php echo $form->lastname; ?></div>
        </div>
        <div><?php echo $form->email; ?></div>
        <div><?php echo $form->telephone; ?></div>
        <div><?php echo $form->gender; ?></div>
        <a href="<?php echo $this->url(array(
            "controller" => "user",
            "action"     => "change"
        )) ?>"
           data-target="#newAddress" class="btn btn-success pull-right">
            <span aria-hidden="true"></span>
            Benutzerdaten ändern
        </a>
        <br><br>

        <h3>Passwort ändern</h3>
        <div class="form-group">
            <label for="password">Aktuelles Passwort</label>
            <input type="password" class="form-control">
        </div>

        <div class="form-group">
            <label for="password">Neues Passwort</label>
            <input type="password" class="form-control">
        </div>

        <div class="form-group">
            <label for="password">Neues Passwort (wiederholen)</label>
            <input type="password" class="form-control">
        </div>
        <a href="<?php echo $this->url(array(
                    'controller' => "user",
                    "action"     => "change"
                )) ?>"
           data-target="#newAddress" class="btn btn-success pull-right">
            <span aria-hidden="true"></span>
                    Passwort ändern
        </a>

    <br><br><br>

        <h3>Adresse</h3>
 <!--        <div class="row">-->
<!--            <div class="col-md-10 col-sm-9 col-xs-9">-->
<!--                <div class="form-group">-->
<!--                    <label for="street">Straße</label>-->
<!--                    <input type="text" class="form-control" value="Musterstraße" readonly>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-md-2 col-sm-3 col-xs-3">-->
<!--                <div class="form-group">-->
<!--                    <label for="street">Nr.</label>-->
<!--                    <input type="text" class="form-control" value="1" readonly>-->
<!--                </div>-->
<!--            </div>-->
<!--            <br>-->
<!--            <div class="col-xs-4">-->
<!--                <div class="form-group">-->
<!--                    <label for="zip">Postleitzahl</label>-->
<!--                    <input type="text" class="form-control" value="123456" readonly>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-xs-8">-->
<!--                <div class="form-group">-->
<!--                    <label for="city">Ort</label>-->
<!--                    <input type="text" class="form-control" value="Musterstadt" readonly>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        <button type="submit" class="btn btn-default"><a href="../address/index">Adresse bearbeiten</a></button>-->
<!--        </form>-->
        <a href="<?php echo $this->url(array(
            'controller' => "user",
            "action"     => "change"
        )) ?>"
           data-target="#newAddress" class="btn btn-success pull-right">
            <span aria-hidden="true"></span>
            Addresse ändern
        </a>
    <br><br><br><br><br><br><br><br><br>
    </div>
</div>