<?php
$form = $this->userForm;

//Nicht ausgegebene Ereignisse des aktuellen Requests
if ($this->unfullfilledRequiredments) {
    echo $this->flashMessages(true);
} else {
    echo $this->flashMessages();
}
?>

<form class="form-group" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>">
<div class="row">
    <div class="col-sm-5 col-sm-offset-1">
        <h1>Profil</h1>
        <h3>Persönliches</h3>
        <div class="row">
            <div class="col-md-12"><?php echo $form->username; ?></div>
            <div class="col-md-6"><?php echo $form->surname; ?></div>
            <div class="col-md-6"><?php echo $form->lastname; ?></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div><?php echo $form->email; ?></div>
                <div><?php echo $form->telephone; ?></div>
            </div>
        </div>

        <div class="row"><div class="col-md-8"><?php echo $form->submit; ?></div></div>
        </form>
        <br><br>
    </div>
</div>
</form>